# This is a basic workflow to help you get started with Actions

name: Deploy on push to master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    
    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
    - run: bun test
      env:
        CI: true
    
    - name: Deploy website
      uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: './dist'
        connection-string: ${{ secrets.AZURE_STATIC_SITE_CONNECTION_STRING }}
    
    # If this guy expires
    # az login
    # az ad sp create-for-rbac --name "GitHubResumeApp" --role contributor --scopes /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName} --sdk-auth
    - name: Azure service principal login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Do other steps
        
    - name: Purge CDN
      run:
        az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait
        
    - name: Azure service principal logout
      run: |
        az logout
